// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DisableSystemProxy() {
  return window['go']['main']['App']['DisableSystemProxy']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnableSystemProxy() {
  return window['go']['main']['App']['EnableSystemProxy']();
}

export function PingHost(arg1) {
  return window['go']['main']['App']['PingHost'](arg1);
}

export function TailLogs(arg1) {
  return window['go']['main']['App']['TailLogs'](arg1);
}
