// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnectRequest):Promise<string>;

export function DisableSystemProxy():Promise<void>;

export function Disconnect():Promise<string>;

export function EnableSystemProxy():Promise<void>;

export function PingHost(arg1:string):Promise<number>;

export function TailLogs(arg1:number):Promise<Array<string>>;
